- Files
    - what is file
    - what is file handling
    - file methods
    - different modes
    - file processing methods
    - Use of 'with' statement


- File
    - File is a named location on desktop used to store some related information
    - ex: .txt,.ipynb, .mp4,.mp3, .pdf,.png, .jpg, .doc etc
    

- File handling
    - CRUD
    - Creating, Reading,Updating, Delete
    - Python too supports file handling and allow users to handle files.

- file methods

    - create
    - open
    - work
    - close
    

- different modes

- r : read mode {default mode}
- w : write mode
- a : append mode
- r+ : both read and write mode
- w+ : both write and read mode
- a+ : both append and read mode



- file processing 
    - Syntax for file opening
        - file_obj = open('filename','filemode')
    - Syntax for file closing
        - file_obj.close()
    - Syntax for reading file data
        - file_obj.read(size)
        

- use of with statement
     - best way to close a file by using the with statement
     - Syntax:
         - with open('filename','filemode') as file_object:

In [22]:
## opening a file

f = open('nandini.txt','r')
if f:
    print('Opened successfully')
f.close()

    

Opened successfully


In [23]:
## reading the data

f = open('nandini.txt')
data = f.read()
print(data)
f.close()




Good evening all 
Welcome to online python workshop which will be conducted by APSSDC


In [26]:
f = open('nandini.txt')
data = f.read(17)
print(data)
f.close()


Good evening all 


In [27]:
a = open('apssdc.txt','w')


In [28]:
b = open ('rain.txt','w')

In [29]:
with open('nandini.txt','w') as f:
    f.write("\nStay home stay safe")

In [30]:
with open('nandini.txt','a') as f:
    f.write("\nThank you")

- File objective methods

    -  seek()
        - Used to change the cursor position
    -  tell()
        - Used to know the cursor position
        

In [40]:
f = open('nandini.txt')
data = f.read(8)
print(f.tell())
f.seek(12)
print(f.tell())
f.close()

8
12


In [44]:
## reading and printing data of file by using functions

def readFile(filename):
    with open(filename,'r') as f:
        filedata = f.read()
    return filedata

print(readFile('nandini.txt'))

Stay home stay safe
Thank you
sdfjasld
owieruoi
cmvnxc,m
oweiru
sdkfjlde97r



In [45]:
## read lines in a file

def readLines(filename):
    return len(readFile(filename).split('\n'))
print(readLines('nandini.txt'))

8


In [46]:
def read_lines(filename):
    with open(filename) as f:
        filedata = f.read()
    return len(filedata.split('\n'))

print(read_lines('nandini.txt'))
        

8


In [49]:
### number of words in file

def no_words(filename):
    c = 0
    with open(filename,'r') as f:
        filedata = f.readlines()
        for line in filedata:
            words_list = line.split()
            c = c+len(words_list)
    return c
no_words('nandini.txt')

            
            

15

In [47]:
l = ['asf dlkfj oertu']
k = []
for i in l:
    r = i.split()
    k.append(r)
print(k)

[['asf', 'dlkfj', 'oertu']]


### Task
    - Similar words count
    - {Stay:1 home:2 stay:1 safe:1 ---}


## Data Science

    - A filed of science that study the data, analyse the data and performs
      various steps on the data to get valuable insights 

In [ ]:
- ram
- color
- 37k
- keybord



- Numpy
    - Sceintific caluculation
- Pandas
    - Data analysis, data manupulation and data cleaning
- Matplotlib
    -  Visulization

## Numpy

- Numerical Python
- Used to do Sceintific caluculation
    - log(), tig(), linear algebra, exp, etc
- we are dealing numpy array kind of data
- execution speed fast than list
- less memory 

    

In [ ]:
## installation

-- pip install numpy
-- import numpy



In [25]:
import numpy as np

In [27]:
## 1 dimensional array

r = np.array([1,2,3,6,5])
print(r)
print(t.ndim)
print(np.__version__)
print(type(r))
print(t.shape)
print(t.itemsize)

[1 2 3 6 5]
2
1.18.5
<class 'numpy.ndarray'>
(2, 2)
4


In [10]:
t = np.array([[1,2],[4,5]])
t

array([[1, 2],
       [4, 5]])

In [9]:
import numpy as np

In [4]:
q = np.array([1,4,5])
print(q)

[1 4 5]


In [5]:
type(q)

numpy.ndarray

In [28]:
y = np.array([[1,2,3],[6,8,4],[3,7,5]])
print(y)

[[1 2 3]
 [6 8 4]
 [3 7 5]]


In [29]:
y.shape

(3, 3)

In [30]:
y.itemsize

4