## Numpy Conti...

In [1]:
import numpy as np

In [7]:
## creating 1d array 

a = np.array([3,5,8])
type(a)
a.ndim

1

In [13]:
## some predefined functions in numpy package

b = np.array([[1,2,3],[7,8,9],[5,6,7]])
print(b.ndim)
print(b.dtype)
print(b.shape)
print(b.size)
print(b.itemsize)
print(np.__version__)

2
int32
(3, 3)
9
4
1.18.5


In [14]:
r = np.array((4,6,7))
r

array([4, 6, 7])

#### range()

In [17]:
## creating array using range function

a1 = np.array(range(9))
print(a1)
a2 = np.array(range(2,10))
print(a2)
a3 = np.array(range(1,10,2))
print(a3)

[0 1 2 3 4 5 6 7 8]
[2 3 4 5 6 7 8 9]
[1 3 5 7 9]


### arange()

In [20]:
### creating array using arange method

b1 = np.arange(9)
print(b1)
b2 = np.arange(2,18)
print(b2)
b3 = np.arange(2,12,4)
print(b3)

[0 1 2 3 4 5 6 7 8]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[ 2  6 10]


### reshape

In [21]:
c = np.arange(20).reshape(5,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [22]:
c = np.arange(20)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
c1 = np.arange(15).reshape(-1,5)
c1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
c1 = np.arange(15).reshape(5,-5)
c1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [31]:
## creating array with ones

o = np.ones((5,6),dtype = int)
o

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [33]:
## creating array with zeros

z = np.zeros((4,6),dtype = int)
z

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [34]:
f = np.full((3,4),89)
f

array([[89, 89, 89, 89],
       [89, 89, 89, 89],
       [89, 89, 89, 89]])

In [35]:
## creating identity matrix

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
t = np.arange(25).reshape(5,5)
t

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
## digonal elements 

np.diag(t)

array([ 0,  6, 12, 18, 24])

## Random
- generates random values in a range
    - random.randint()
        - random.randint()
        - random.randint(,)
        - random.randint(,,)
        - random.randint(,())
    - random.random()
    - random.randn()
    
     
    

In [46]:
r = np.random.randint(10)
print(r)
r1 = np.random.randint(10,40)
print(r1)
r2 = np.random.randint(1,10,4)
print(r2)
r3 = np.random.randint(10,100,(2,4))
print(r3)

9
26
[9 2 3 8]
[[94 44 39 16]
 [89 74 46 75]]


In [47]:
## random.random()
## random.randn()

t1 = np.random.random(10)
t1

array([0.7194501 , 0.05483956, 0.941808  , 0.16746322, 0.61221171,
       0.50042948, 0.24935316, 0.07166127, 0.92797032, 0.34596527])

In [49]:
t2 = np.random.randn(10)
t2

array([ 0.11829806, -0.71593051, -0.2990695 , -0.83863479, -0.08481896,
        1.12220898,  0.11524859,  0.80969708, -1.31483295, -2.05164333])

## Slicing

In [ ]:
[start:end:step]


In [50]:
r5 = np.random.randint(10,100,(4,4))
r5

array([[47, 26, 79, 41],
       [83, 18, 63, 30],
       [86, 74, 30, 14],
       [93, 75, 53, 82]])

In [51]:
r5[:]

array([[47, 26, 79, 41],
       [83, 18, 63, 30],
       [86, 74, 30, 14],
       [93, 75, 53, 82]])

In [52]:
r5[::]

array([[47, 26, 79, 41],
       [83, 18, 63, 30],
       [86, 74, 30, 14],
       [93, 75, 53, 82]])

In [53]:
r5[:3]

array([[47, 26, 79, 41],
       [83, 18, 63, 30],
       [86, 74, 30, 14]])

In [55]:
r5[2:3]

array([[86, 74, 30, 14]])

In [56]:
r5

array([[47, 26, 79, 41],
       [83, 18, 63, 30],
       [86, 74, 30, 14],
       [93, 75, 53, 82]])

In [58]:
r5>50

array([[False, False,  True, False],
       [ True, False,  True, False],
       [ True,  True, False, False],
       [ True,  True,  True,  True]])

In [59]:
r5[r5>50]

array([79, 83, 63, 86, 74, 93, 75, 53, 82])

In [60]:
r5[r5>50].sum()

688

In [61]:
r5.sum()

894

In [62]:
a = np.array([[2,3],[5,6]])
a

array([[2, 3],
       [5, 6]])

In [63]:
a.sum()

16

## Mathmatical operations

In [64]:
np.matrix("1,2;3,4")

matrix([[1, 2],
        [3, 4]])

In [65]:
a = np.array([[2,3],[5,6]])
a

array([[2, 3],
       [5, 6]])

In [67]:
b = np.array([[8,5],[3,5]])
b

array([[8, 5],
       [3, 5]])

In [68]:
np.add(a,b)

array([[10,  8],
       [ 8, 11]])

In [69]:
np.subtract(a,b)

array([[-6, -2],
       [ 2,  1]])

In [70]:
np.matmul(a,b)

array([[25, 25],
       [58, 55]])

In [71]:
np.multiply(a,b)

array([[16, 15],
       [15, 30]])

In [72]:
np.dot(a,b)

array([[25, 25],
       [58, 55]])

## Scientific Computation

In [73]:
m = np.arange(20).reshape(5,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [78]:
print(np.mean(m))
print(np.median(m))
print(np.std(m))
print(a.dot(b))

9.5
9.5
5.766281297335398
[[25 25]
 [58 55]]


## Logarithams and Exponentials

In [79]:
np.log(0)

<ipython-input-79-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [80]:
np.log(1)

0.0

In [81]:
np.log(3)

1.0986122886681098

In [82]:
np.log([1,2,3,4])

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [83]:
np.exp(1)

2.718281828459045

In [84]:
np.exp([3,7,8])

array([  20.08553692, 1096.63315843, 2980.95798704])

In [85]:
np.sin(3)

0.1411200080598672

In [86]:
np.cos(45)

0.5253219888177297

In [87]:
np.tan(34)

-0.6234989627162255

In [88]:
np.cot(45)

AttributeError: module 'numpy' has no attribute 'cot'

In [89]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [92]:
r = np.linspace(1,10,5)

In [93]:
r

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

## Pandas

- Means PanelData
- one of the data science packages
- Used data manupulation, analysis and cleaning
- It contains two data structures 
    - 1.Series
    - 2.DataFrames
- A series is a sequence of data
- A data frame is a data with rows and columns

   

In [ ]:
# installation

-- pip install pandas
- import pandas

In [1]:
import pandas as pd

In [2]:
pd.__version__

'1.0.5'

## Series

In [4]:
st = 4
pd.Series(st)

0    4
dtype: int64

In [5]:
st1 = "hi hello good evening".split()
pd.Series(st1)

0         hi
1      hello
2       good
3    evening
dtype: object

In [8]:
st2 = [123,'acds',89.54]
pd.Series(st2, index = ['int','str','float'])

int        123
str       acds
float    89.54
dtype: object

In [9]:
st2 = (123,'acds',89.54)
pd.Series(st2, index = ['int','str','float'])

int        123
str       acds
float    89.54
dtype: object

In [10]:
dic = {'key1':123,'key2':'hello','key3':5.6}
pd.Series(dic)

key1      123
key2    hello
key3      5.6
dtype: object

### DataFrames


In [12]:
s = "ok madam".split()
pd.DataFrame(s)

0
0     ok
1  madam

In [14]:
l = [1,4,9.6,'adsf']
pd.DataFrame(l, index = [1,2,3,4])

0
1     1
2     4
3   9.6
4  adsf

In [15]:
l = (1,4,9.6,'adsf')
pd.DataFrame(l, index = [1,2,3,4])

0
1     1
2     4
3   9.6
4  adsf

In [17]:
dic = {'Names':['firstname','secondname','thirdname'],'marks':[9.8,9.6,9.4],
       'id_no':['N130661','N130662','N130663']}
pd.DataFrame(dic,index=['stu1','stu2','stu3'])

Names  marks    id_no
stu1   firstname    9.8  N130661
stu2  secondname    9.6  N130662
stu3   thirdname    9.4  N130663